# basic info

name: "IT's Shiny"
description: "IT's Shiny"
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "http://s.cn.bing.net/az/hprichbg/rb/TulfesTyrol_ZH-CN11110819205_1920x1080.jpg"
author: "shinyzhu"
author_image: "/assets/images/author.jpg"
email: shiny@shinyzhu.com
permalink: /:categories/:title
paginate: 5
paginate_path: /page/:num
excerpt_separator: ''

# Jekyll configurations

safe: true
markdown: rdiscount
pygments: true
timezone: Asia/Shanghai
highlighter: pygments

baseurl: "http://shinyzhu.com"

commentsystem: disqus
disqus: "shinyzhu"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/shinyzhu
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/shinyzhu
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: feed
    url:  /feed.xml
    desc: Subscribe to my feed

menu:
  - title:  Home [主页]
    url:  /

  - title: Blog [博客]
    url: /blog

  - title: Work [作品]
    url: /work

  - title:  Me [我]
    url:  /about


# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-1645044-4
