# basic info

email: shiny@shinyzhu.com
permalink: /:categories/:title
paginate: 10
paginate_path: /page/:num
excerpt_separator: ''

# Jekyll configurations

safe: true
markdown: rdiscount
pygments: true
timezone: Asia/Shanghai

# social info
github: shinyzhu
